FROM node:16-alpine AS development
ENV NODE_OPTIONS=--max-old-space-size=2048
WORKDIR /api

COPY package*.json yarn.lock ./
RUN yarn install

COPY . .
RUN yarn run build

FROM node:16-alpine AS run
ENV NODE_OPTIONS=--max-old-space-size=2048

# Set node env to prod
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Set Working Directory
WORKDIR /api

# Copy all from development stage
COPY --from=development /api/ .

EXPOSE 3001

# Run app
CMD ["yarn", "run:dev"]

# Example Commands to build and run the dockerfile
# docker build -t thomas-nest .
# docker run thomas-nest
