version: '3.1'
services:
  psql-local:
    container_name: postgresdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backendpass
      - POSTGRES_DB=tcit_api_dev
